"""
Example usage of the Universal AI Optimizer
"""

from universal_ai_optimizer.core.optimizer import UniversalAIOptimizer, OptimizerConfig

# Mock model adapter for demonstration
class MockModelAdapter:
    """A mock model adapter that simulates a language model"""
    
    def __init__(self, model_name="mock-model"):
        self.model_name = model_name
    
    def generate(self, prompt, max_length=100, temperature=0.7, **kwargs):
        """Simulate text generation"""
        # In a real implementation, this would call the actual model
        import time
        time.sleep(0.1)  # Simulate processing delay
        
        # Return a simple mock response
        return f"Mock response to: '{prompt[:50]}...' (generated by {self.model_name})"

def main():
    """Demonstrate the Universal AI Optimizer"""
    print("Universal AI Optimizer - Example Usage")
    print("=" * 50)
    
    # Create optimizer configuration
    config = OptimizerConfig()
    
    # Optionally, customize configuration
    config.context_compression.compression_ratio = 0.4
    config.execution.quantization = "int8"
    config.cache.enabled = True
    config.verification.enabled = True
    
    # Initialize the optimizer
    optimizer = UniversalAIOptimizer(config)
    
    # Register a mock model adapter
    mock_adapter = MockModelAdapter("demo-model-v1")
    optimizer.register_model_adapter("mock", mock_adapter)
    
    # Example prompt and context
    prompt = "Explain the concept of quantum computing in simple terms."
    context = {
        "conversation_history": [
            {"role": "user", "content": "What is quantum mechanics?"},
            {"role": "assistant", "content": "Quantum mechanics is a fundamental theory in physics..."}
        ],
        "documents": [
            "Quantum computing uses quantum bits or qubits...",
            "Unlike classical bits, qubits can be in superposition states..."
        ]
    }
    
    print(f"Original prompt: {prompt}")
    print(f"Context keys: {list(context.keys())}")
    print()
    
    # Run optimization
    print("Running optimization...")
    result = optimizer.optimize(prompt, context, model_adapter=mock_adapter)
    
    # Display results
    print("\nOptimization Results:")
    print("-" * 30)
    print(f"Optimized prompt: {result.optimized_prompt[:100]}...")
    print(f"Latency: {result.latency_ms:.2f}ms")
    print(f"Token savings: {result.token_savings:.1f}%")
    print(f"Verification score: {result.verification_score:.3f}")
    print(f"Resource savings: {result.resource_savings}")
    
    # Show metrics
    print("\nSystem Metrics:")
    print("-" * 30)
    metrics = optimizer.get_metrics()
    for module_name, module_metrics in metrics.items():
        if isinstance(module_metrics, dict):
            print(f"{module_name}: {module_metrics.get('enabled', 'N/A')}")

if __name__ == "__main__":
    main()